"""Update appointment Time

Revision ID: 48c6d610b7ba
Revises: 65e6ae4a8c0b
Create Date: 2024-06-05 00:11:13.043291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48c6d610b7ba'
down_revision = '65e6ae4a8c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointmentTime',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointmentTime',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
