"""Initial migration.

Revision ID: 67018bbed12a
Revises: 
Create Date: 2024-06-01 20:10:45.010495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67018bbed12a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('appointmentDate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('appointmentTime',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('doctor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('_updatedDate')
        batch_op.drop_column('_createdDate')
        batch_op.drop_column('_owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_owner', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('_createdDate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('_updatedDate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('doctor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('appointmentTime',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('appointmentDate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
