"""Add date

Revision ID: b04b0bc3e17d
Revises: c30c4300c987
Create Date: 2024-06-02 01:33:28.739793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04b0bc3e17d'
down_revision = 'c30c4300c987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
